ARG UBUNTU_VERSION=resolute
FROM ubuntu:${UBUNTU_VERSION}


SHELL ["/bin/bash", "-c"]
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get upgrade --yes --no-install-recommends --no-install-suggests && \
    apt-get install --yes --no-install-recommends --no-install-suggests \
    ca-certificates && \
    rm -rf /var/lib/apt/lists/*


# Install baseline packages
RUN apt-get update && \
    apt-get install --yes --no-install-recommends --no-install-suggests \
    bash \
    build-essential \
    curl \
    htop \
    jq \
    locales \
    man \
    pipx \
    python3 \
    python3-pip \
    software-properties-common \
    sudo \
    systemd \
    systemd-sysv \
    unzip \
    vim \
    wget \
    rsync \
    iproute2 && \
# Install latest Git using their official PPA
    add-apt-repository ppa:git-core/ppa && \
    apt-get install --yes git \
    && rm -rf /var/lib/apt/lists/*


# Generate the desired locale (en_US.UTF-8)
RUN locale-gen en_US.UTF-8

# Make typing unicode characters in the terminal work.
ENV LANG=en_US.UTF-8
ENV LANGUAGE=en_US.UTF-8
ENV LC_ALL=en_US.UTF-8

RUN curl -fsSL https://deb.nodesource.com/setup_20.x | bash && apt-get install -y nodejs && rm -rf /var/lib/apt/lists/*

# Remove the `ubuntu` user and add a user `coder` so that you're not developing as the `root` user
RUN userdel -r ubuntu

ARG OPENCODE_VERSION=1.18.4
ARG USERNAME=coder
ARG USER_UID=3001
ARG USER_GID=3001
RUN groupadd --gid ${USER_GID} ${USERNAME} \
    && useradd -s /bin/bash --uid ${USER_UID} --gid ${USER_GID} -m ${USERNAME} \
    && usermod -aG sudo ${USERNAME} \
    && echo "${USERNAME} ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/90-${USERNAME} \
    && chmod 0440 /etc/sudoers.d/90-${USERNAME}   


# Workspace & Permissions
WORKDIR /workspaces
RUN chown -R ${USERNAME}:${USERNAME} /workspaces
USER coder


RUN pipx ensurepath

#RUN curl -fsSL https://opencode.ai/install | bash
####
RUN curl -fsSL https://opencode.ai/install | bash

ENV PATH="/home/coder/.opencode/bin:$PATH"

RUN mkdir -p /home/coder/.config/opencode \
             /home/coder/.local/share/opencode

COPY opencode.json /home/coder/.config/opencode/opencode.json
